"""initial_migration

Revision ID: 0c26df38406b
Revises: 
Create Date: 2026-08-18 14:29:47.628894
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0c26df38406b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sous_metiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metier_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['metier_id'], ['metiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('metier_id', sa.Integer(), nullable=True),
    sa.Column('sous_metier_id', sa.Integer(), nullable=True),
    sa.Column('type_abonnement', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metier_id'], ['metiers.id'], ),
    sa.ForeignKeyConstraint(['sous_metier_id'], ['sous_metiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telephone'), 'users', ['telephone'], unique=True)
    op.create_table('quotas_utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requetes_restantes_gratuites', sa.Integer(), nullable=False),
    sa.Column('date_fin_premium', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transactions_mobile_money',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('devise', sa.String(length=5), nullable=False),
    sa.Column('operateur', sa.String(length=20), nullable=False),
    sa.Column('statut_paiement', sa.String(length=20), nullable=False),
    sa.Column('type_achat', sa.String(length=30), nullable=False),
    sa.Column('reference_externe', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_mobile_money_user_id'), 'transactions_mobile_money', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_mobile_money_user_id'), table_name='transactions_mobile_money')
    op.drop_table('transactions_mobile_money')
    op.drop_table('quotas_utilisateurs')
    op.drop_index(op.f('ix_users_telephone'), table_name='users')
    op.drop_table('users')
    op.drop_table('sous_metiers')
    op.drop_table('metiers')
    # ### end Alembic commands ###
